apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: todoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
        app: todoapp
    spec:
      containers:
      - name: mongo
        image: mongo:5.0
        resources:
        ports:
        - containerPort: 27017
        volumeMounts: 
        - name: mongo-storage
          mountPath: /data/db  
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: db-pv-vol-claim # comes from pv-claim file  
